# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\x12\x0c\x64\x61ta_example\"\x90\x04\n\x07\x44\x61taVal\x12\x33\n\x07\x62uffers\x18\x01 \x03(\x0b\x32\".data_example.DataVal.BuffersEntry\x12\x41\n\x11global_conditions\x18\x02 \x01(\x0b\x32&.data_example.DataVal.GlobalConditions\x1a\x9b\x01\n\nDataBuffer\x12\r\n\x05shape\x18\x01 \x03(\x05\x12\x15\n\rsampling_rate\x18\x02 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x03 \x02(\x0c\x12\x32\n\tprecision\x18\x04 \x01(\x0e\x32\x1f.data_example.DataVal.Precision\x12\x11\n\tdata_path\x18\x05 \x01(\t\x12\x12\n\nstart_time\x18\x06 \x01(\x02\x1a?\n\x10GlobalConditions\x12\r\n\x05tonic\x18\x01 \x01(\x02\x12\x0c\n\x04raga\x18\x02 \x01(\x05\x12\x0e\n\x06singer\x18\x03 \x01(\x05\x1aP\n\x0c\x42uffersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12/\n\x05value\x18\x02 \x01(\x0b\x32 .data_example.DataVal.DataBuffer:\x02\x38\x01\"\\\n\tPrecision\x12\x0b\n\x07\x46LOAT16\x10\x00\x12\x0b\n\x07\x46LOAT32\x10\x01\x12\x0b\n\x07\x46LOAT64\x10\x02\x12\t\n\x05INT16\x10\x03\x12\t\n\x05INT32\x10\x04\x12\t\n\x05INT64\x10\x05\x12\x07\n\x03RAW\x10\x06')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DATAVAL_BUFFERSENTRY']._options = None
  _globals['_DATAVAL_BUFFERSENTRY']._serialized_options = b'8\001'
  _globals['_DATAVAL']._serialized_start=29
  _globals['_DATAVAL']._serialized_end=557
  _globals['_DATAVAL_DATABUFFER']._serialized_start=161
  _globals['_DATAVAL_DATABUFFER']._serialized_end=316
  _globals['_DATAVAL_GLOBALCONDITIONS']._serialized_start=318
  _globals['_DATAVAL_GLOBALCONDITIONS']._serialized_end=381
  _globals['_DATAVAL_BUFFERSENTRY']._serialized_start=383
  _globals['_DATAVAL_BUFFERSENTRY']._serialized_end=463
  _globals['_DATAVAL_PRECISION']._serialized_start=465
  _globals['_DATAVAL_PRECISION']._serialized_end=557
# @@protoc_insertion_point(module_scope)
